name: 🐛 Bug Report
description: Report a bug or unexpected behavior in InteractiveFlow.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us investigate.

  - type: input
    id: version
    attributes:
      label: InteractiveFlow Version
      description: What version of InteractiveFlow are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: djs-version
    attributes:
      label: Discord.js Version
      description: What version of discord.js are you using?
      placeholder: "14.18.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: "20.x"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Create a FlowPaginator with...
        2. Call send() on...
        3. Click the next button...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the actual behavior...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue.
      render: typescript

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or error logs.
